version: "3.7"

volumes:
  kong_data:

networks:
  kong-network:

services:
  kong-db:
    image: postgres:9.6
    container_name: kong-db
    restart: always
    networks:
      - kong-network
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    ports:
      - "5432:5432"

  kong-migration:
    image: kong:latest
    container_name: kong-migration
    command: kong migrations bootstrap
    networks:
      - kong-network
    restart: on-failure
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    depends_on:
      - kong-db

  kong:
    image: kong:latest
    container_name: kong
    restart: always
    networks:
      - kong-network
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    depends_on:
      - kong-migration
    ports:
      - "80:8000"
      - "8001:8001"
      - "443:8443"
      - "8444:8444"

  konga-prepare:
    image: pantsel/konga:latest
    container_name: konga-prepare
    command: "-c prepare -a postgres -u postgresql://kong:kong@kong-db:5432/konga"
    networks:
      - kong-network
    restart: on-failure
    depends_on:
      - kong

  konga:
    image: pantsel/konga:latest
    container_name: konga
    restart: always
    networks:
      - kong-network
    environment:
      DB_ADAPTER: postgres
      DB_URI: postgresql://kong:kong@kong-db:5432/konga
      NODE_ENV: production
    depends_on:
      - konga-prepare
    ports:
      - "1337:1337"

  service-masters-1:
    build: ./services/masters
    container_name: app-masters-1
    command: npm run prod
    depends_on:
      - konga
    networks:
      - kong-network

  service-masters-2:
    build: ./services/masters
    container_name: app-masters-2
    command: npm run prod
    depends_on:
      - konga
    networks:
      - kong-network

  service-orders-1:
    build: ./services/orders
    container_name: app-orders-1
    command: npm run prod
    depends_on:
      - konga
    networks:
      - kong-network

  service-orders-2:
    build: ./services/orders
    container_name: app-orders-2
    command: npm run prod
    depends_on:
      - konga
    networks:
      - kong-network

  service-users-1:
    build: ./services/users
    container_name: app-users-1
    command: npm run prod
    depends_on:
      - konga
    networks:
      - kong-network

  service-users-2:
    build: ./services/users
    container_name: app-users-2
    command: npm run prod
    depends_on:
      - konga
    networks:
      - kong-network
